version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_TTS_LANGUAGE=en
      - DEFAULT_STT_LANGUAGE=en
      - WHISPER_MODEL_SIZE=tiny
      - DEBUG_MODE=true
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped 